const GET_CURRENT_POSITION = "GET_CURRENT_POSITION"
const ADD_MAP_POSITION = "ADD_MAP_POSITION"
const RESET_GET_POSITION = "RESET_GET_POSITION"
const SET_SELECT_CITY = "SET_SELECT_CITY"
const SET_LOGIN_STATE = "SET_LOGIN_STATE"
const CLEAR_SEARCH_HISTORY = "CLEAR_SEARCH_HISTORY"
const RESET_SURROUNDING_POSITION = "RESET_SURROUNDING_POSITION"
const SET_SHIP_ADDRESS = "SET_SHIP_ADDRESS"

export {
  GET_CURRENT_POSITION,
  ADD_MAP_POSITION,
  RESET_GET_POSITION,
  SET_SELECT_CITY,
  SET_LOGIN_STATE,
  CLEAR_SEARCH_HISTORY,
  RESET_SURROUNDING_POSITION,
  SET_SHIP_ADDRESS
}